[package]
name = "rome_markdown_factory"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rome_rowan = { version = "0.0.1",path = "../rome_rowan" }
rome_markdown_syntax = { version = "0.0.0",path = "../rome_markdown_syntax" }

